# Name
REPO_NAME           ?= Korean Train Set

# File name of *.grf, *.tar and so on
BASE_FILENAME       ?= ko_train_set

# Versoin
VERSION             ?= 2.0.0-alpha1
REPO_BRANCH_VERSION ?= 0
RECENT_UPDATED		?= 2020.11.06

# Author's information
AUTHOR_WEBSITE      ?= https://telk.kr
AUTHOR_EMAIL        ?= telk5093@gmail.com

# If needed, declare the minimum NML requirements
REQUIRED_NML_BRANCH  = 0.4
# MIN_NML_REVISION   = 0